---

- name: Hidding Secrets
  hosts: servers
  become: yes

  vars_files:
    - secrets.yml
  
  tasks:
    - name: Show Password
      debug:
        msg: "My Password is {{ password }}"
      no_log: true

    - name: Show api-key
      debug:
        msg: "My API-Key is {{ api_key }}"
      no_log: true
